### ISSUE TITLE
Не срабатывает переход в приложение, если авторизация происходит через браузер

### ISSUE THREAD

**Issue by BulatMukhutdinov** [yandexmobile/yandex-login-sdk-android#16]
Версия библиотеки: 3.1.0
targetSdkVersion приложения: 31, поэтому часть зависимостей приходится downgrade'ить
```
force 'androidx.appcompat:appcompat-resources:1.4.2'
force 'androidx.appcompat:appcompat:1.4.2'
force 'androidx.activity:activity:1.5.1'
force 'androidx.activity:activity-ktx:1.5.1'
force 'androidx.browser:browser:1.4.0'
force 'androidx.savedstate:savedstate-ktx:1.2.0'
force 'androidx.savedstate:savedstate:1.2.0'
force 'androidx.lifecycle:lifecycle-livedata-core:2.5.1'
force 'androidx.lifecycle:lifecycle-service:2.2.0'
```

При запросе авторизации без установленных на телефоне приложений яндекса (через бразуер), после подтверждения авторизации, бразуер не может перекинуть обратно в приложение. Остается на экране с ошибкой:
![telegram-cloud-photo-size-2-5330126059141715481-y](https://github.com/yandexmobile/yandex-login-sdk-android/assets/1418811/4ad73ff0-23eb-44ab-b770-efc789671d85)

При этом, если перейти по ссылке "установить", то гугл плей показывает, что приложение уже установлено

**Comment by BulatMukhutdinov** [comment]
Оказывается при создании приложения в консоли надо активировать Веб-сервисы и прописать там дип линк на своё приложение. Неплохо было бы это указать в документации.

**Comment by aakumykov** [comment]
Но это [ломает публикацию приложения в Google Play](https://github.com/yandexmobile/yandex-login-sdk-android/issues/18).
