### ISSUE TITLE
Where can I find source code for 2.1.1?

### ISSUE THREAD

**Issue by sirekanyan** [yandexmobile/yandex-login-sdk-android#3]
Hi,

I've found yandex authsdk 2.1.1 in public repository (eg: maven central https://mvnrepository.com/artifact/com.yandex.android/authsdk/2.1.1)

Do you plan to publish its source code? I only see 2.1.0 in current github repository.

Thank you!

**Comment by HotIceCream** [comment]
Published https://github.com/yandexmobile/yandex-login-sdk-android/tree/release-2.1.1
