### ISSUE TITLE
Не удаётся авторизоваться, если на телефоне установлено любое приложение Яндекса.

### ISSUE THREAD

**Issue by skobelev-dmitriy** [yandexmobile/yandex-login-sdk-android#7]
Столкнулся с такой же ошибкой.
Проверял на 2-х версиях (2.0.0, 2.1.1). Версии Android SDK 27.
`scopes.add("account-info")`
 В логах
`I/ActivityManager: START u0 {cmp=kct.ru.spclub/com.yandex.authsdk.internal.AuthSdkActivity (has extras)} from uid 10082
I/ActivityManager: START u0 {act=com.yandex.auth.action.YA_SDK_LOGIN pkg=ru.yandex.searchplugin cmp=ru.yandex.searchplugin/com.yandex.passport.internal.ui.authsdk.AuthSdkActivity (has extras)} from uid 10082
I/chatty: uid=10084 ru.yandex.searchplugin:passport identical 2 lines
I/chatty: uid=10084 ru.yandex.searchplugin:passport identical 2 lines
I/chatty: uid=10084 ru.yandex.searchplugin:passport identical 2 lines
I/chatty: uid=10084 ru.yandex.searchplugin:passport identical 2 lines
I/chatty: uid=10084 ru.yandex.searchplugin:passport identical 2 lines
I/chatty: uid=10084 ru.yandex.searchplugin:passport identical 1 line
I/chatty: uid=10084 ru.yandex.searchplugin:passport identical 2 lines
I/chatty: uid=10084 ru.yandex.searchplugin:passport identical 3 lines
I/chatty: uid=10084 ru.yandex.searchplugin:passport identical 2 lines
I/chatty: uid=10084 ru.yandex.searchplugin:passport identical 1 line
I/chatty: uid=10084 ru.yandex.searchplugin:passport identical 2 lines
I/chatty: uid=10084 ru.yandex.searchplugin:passport identical 2 lines
I/chatty: uid=10084 ru.yandex.searchplugin:passport identical 1 line
I/chatty: uid=10084 ru.yandex.searchplugin:passport identical 2 lines
I/chatty: uid=10084 ru.yandex.searchplugin:passport identical 2 lines
I/chatty: uid=10084 ru.yandex.searchplugin:passport identical 2 lines
D/SurfaceFlinger: duplicate layer name: changing ru.yandex.searchplugin/com.yandex.passport.internal.ui.authsdk.AuthSdkActivity to ru.yandex.searchplugin/com.yandex.passport.internal.ui.authsdk.AuthSdkActivity#1
I/chatty: uid=10084 ru.yandex.searchplugin:passport identical 2 lines
I/chatty: uid=10084 ru.yandex.searchplugin:passport identical 2 lines
I/chatty: uid=10084 ru.yandex.searchplugin:passport identical 3 lines
I/chatty: uid=10084 ru.yandex.searchplugin:passport identical 2 lines
I/chatty: uid=10084 ru.yandex.searchplugin:passport identical 1 line
I/chatty: uid=10084(ru.yandex.searchplugin) RenderThread identical 1 line
I/ActivityManager: Displayed ru.yandex.searchplugin/com.yandex.passport.internal.ui.authsdk.AuthSdkActivity: +370ms (total +505ms)`

_Originally posted by @skobelev-dmitriy in https://github.com/yandexmobile/yandex-login-sdk-android/issues/6#issuecomment-760709101_

**Comment by kraa** [comment]
Скорее всего scope некорректный 
Чтобы получить список доступных скоупов, в браузере открой ссылку 

[https://oauth.yandex.ru/client/<app_id>/info](https://oauth.yandex.ru/client/<app_id>/info)

Где <app_id> - id твоего приложения.

**Comment by skobelev-dmitriy** [comment]
Благодарю, вроде наладилось. Сам просто не смог найти эту ссылку.
