### ISSUE TITLE
Приложение не запускается после обновления на targetSdk=31

### ISSUE THREAD

**Issue by pavelperc** [yandexmobile/yandex-login-sdk-android#8]
## Проблема
При попытке запуска приложения с targetSdk=31, выводится такая ошибка:

`
Installation failed due to: 'Failed to commit install session 858350124 with command cmd package install-commit 858350124. Error: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl858350124.tmp/base.apk (at Binary XML file line #1095): com.yandex.authsdk.internal.BrowserDataActivity: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present'
`

## Причина
Android 12 требует явно указывать `exported:true/false` для активити в манифесте, если активити содержит intent-filter. https://developer.android.com/about/versions/12/behavior-changes-12#exported

## Решение
В манифест нужно добавить `exported:true`:
https://github.com/yandexmobile/yandex-login-sdk-android/blob/master/lib/src/main/AndroidManifest.xml#L31

**Comment by pavelperc** [comment]
@HotIceCream Я видел исправление в одном из последних коммитов https://github.com/yandexmobile/yandex-login-sdk-android/commit/11ef81cf6df59dc867c4818a1e11303161c8851d, но новая версия не была выпущена https://yandex.ru/dev/mobileauthsdk/doc/sdk/concepts/android/. Как скоро ждать выход новой версии?

**Comment by avstaim** [comment]
> @HotIceCream Я видел исправление в одном из последних коммитов [11ef81c](https://github.com/yandexmobile/yandex-login-sdk-android/commit/11ef81cf6df59dc867c4818a1e11303161c8851d), но новая версия не была выпущена https://yandex.ru/dev/mobileauthsdk/doc/sdk/concepts/android/. Как скоро ждать выход новой версии?

Версия проходит внутреннее тестирование и будет выпущена в течение недели.

**Comment by avstaim** [comment]
зарелизили 2.3.1, исправлено
